apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: loadtestapplicationset
spec:
  generators:
  - git:
      repoURL: https://github.com/sabababoy/distributed_test.git
      revision: HEAD
      directories:
      - path: Kubernetes
  template:
    metadata:
      name: testname
    spec:
      project: default
      source:
        repoURL: https://github.com/sabababoy/distributed_test.git
        targetRevision: HEAD
        path: Kubernetes
      destination:
        server: localhost:8080
        namespace: default
