apiVersion: v1
kind: Service
metadata:
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  type: NodePort
  ports:
    - targetPort: 22
      port: 22
      nodePort: 30022
      name: ssh
    - targetPort: 8080
      port: 8080
      nodePort: 30088
      name: server
  selector: 
    jmeter_mode: master
