apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: master
  template:
    metadata:
      labels:
        jmeter_mode: master
    spec:
      containers:
      - name: jmeter-master
        image: sabababoy/jmeter:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "./set_ssh; bash Scripts/start-master.sh; while true; do sleep 30; done;" ]
        
        ports:
        - containerPort: 60000
          containerPort: 22
        # env:
        #   - name: MY_POD_IP
        #     valueFrom:
        #       fieldRef:
        #         fieldPath: status.podIP
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 512Mi
