apiVersion: v1
kind: Service
metadata:
  name: jmeter-master-svc
  labels:
    jmeter_mode: master
spec:
  type: NodePort
  ports:
    - targetPort: 22
      port: 22
      nodePort: 30022 
  selector: 
    jmeter_mode: master
